# Generated by Django 3.1.7 on 2021-03-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='order_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
