# Generated by Django 3.1.7 on 2021-03-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_products_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='order_quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
